steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/myimage', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/myimage']

  # Entrypoint, timeout and environment variables
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   timeout: 240s
  #   args: ['compute', 'instances', 
  #          'create-with-container', 'my-vm-name',
  #          '--container-image', 
  #          'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/myimage']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - name: 'ubuntu'
    entrypoint: bash
    args: 
      - '-c'
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
        mkdir zap
        tar -xvf ZAP_2.11.1_Linux.tar.gz
        cd ZAP_2.11.1
        ./zap.sh -cmd -quickurl https://act.greensight.ai -quickprogress -quickout ../zap_report.html 
   


artifacts:
  objects:
    location: 'gs://cdnstoragebucket001241'
    paths:
      - zap_report.html 